### ISSUE TITLE
enabling usage of minio

### ISSUE THREAD

**Issue by HenryGeorgist** [water-tech-repos/wat-hydrograph-stats-py#19]
https://github.com/water-tech-repos/wat-hydrograph-stats-py/blob/9fe0463abf3429aedc724519023761a46b410333/tests/aws_integration_test.py#L17

In the other sdk's we enable an env parameter called S3_MOCK where if true we set aws force path style to true, we set the endpoint, and we set the protocol to http instead of https.

https://github.com/USACE/wat-java-sdk/blob/b214177bece2a528d3a970336384303f8d9b5a77/src/main/java/usace/wat/plugin/Utilities.java#L131

https://github.com/USACE/filestore/blob/6484811f7b135c982f7484d6f9bc924fc7de7626/filestore.go#L97

that way we can test with minio locally

**Comment by thwllms** [comment]
@HenryGeorgist we're mocking S3 locally here: https://github.com/water-tech-repos/wat-hydrograph-stats-py/blob/main/docker-compose.test.yml#L10

Sorry if I'm not understanding. In the 'integration tests' here a minio container is spinning up and we point to the minio container by specifying a custom `endpoint_url` with the `boto3` library.
https://github.com/water-tech-repos/wat-hydrograph-stats-py/blob/main/tests/aws_integration_test.py#L14
https://github.com/water-tech-repos/wat-hydrograph-stats-py/blob/main/tests/aws_integration_test.py#L21
https://github.com/water-tech-repos/wat-hydrograph-stats-py/blob/main/tests/aws_integration_test.py#L31

**Comment by HenryGeorgist** [comment]
ok sorry i missed that detail. i see it now. 

you arent getting a cors? i would suspect the way you connect to minio would be http rather than https, which needs to be set in the aws configruation i think.

**Comment by thwllms** [comment]
No worries. The tests pass; not getting a CORS error. When the tests are run with the [integration_tests.sh](https://github.com/water-tech-repos/wat-hydrograph-stats-py/blob/main/integration-tests.sh) script (which spins up the `docker-compose.test.yml` and runs the tests), that `S3_ENDPOINT` is set with an environment variable to point to the minio container (`http://minio:9990`): 
https://github.com/water-tech-repos/wat-hydrograph-stats-py/blob/main/docker-compose.test.yml#L30

**Comment by HenryGeorgist** [comment]
yeah i saw that test, and how you set the endpoint. cool im glad it is all working. sorry for the confusion

**Comment by thwllms** [comment]
No problem! Closing this issue, then.
